version: '3.8'
services:
  messagewall:
    image: gybeyond/messagewall:latest
    container_name: messagewall
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_PATH=/app/data/messages.db
    volumes:
      - ./data:/app/data
